highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
port: 4000
safe: true

title: Mohammad Saad's Resume
name: Mohammad Saad
nickname: mohsaad
email: christurner@me.com
email_full: mailto:youremail@me.com
website: https://mohsaad.com
website_full: https://mohsaad.com
github: mohsaad
twitter: mohsaad230
linkedin: mohsaad


baseurl: "/"




######################################
### Blog details
######################################
blog_url: "/blog"

author:
  #  facebook:         your-id
  #   youtubeUser:      your-id
  #  youtubeChannel:   your-id
  #  twitter:          your-id
  github:           mohsaad
  #  stackoverflow:    your-id
  #  quora:            your-id
  linkedin:         mohsaad
  #  pinterest:        your-id
  #  googlePlus:       your-id
  instagram:        mohsaad023
  #  reddit:           your-id
  #  medium:           your-id
  #  tumblr:           your-id
  #  email:            your-id@your-email.com

# Navigation
nav:
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Reading list"
    url:            "/reading"
  - name:           "Quotes"
    url:            "/quotes"
  - name:           "Resume"
    url:            "/../"


# needed for travis-ci build
exclude: [vendor, _old]
