highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
rdiscount:
  extensions: [smart]
permalink: :title.html
port: 8000
safe: false

title: Mohammad Saad's Resume
name: Mohammad Saad
nickname: mohsaad
email: christurner@me.com
email_full: mailto:youremail@me.com
website: https://mohsaad.com
website_full: https://mohsaad.com


baseurl: "/"

# Gems
gems: [jekyll-paginate]

# Used for compatibility
plugins: [jekyll-paginate]
plugins_dir: [jekyll-paginate]


######################################
### Blog details
######################################
blog_url: "/blog"

author:
  #  facebook:         your-id
  #   youtubeUser:      your-id
  #  youtubeChannel:   your-id
  #  twitter:          your-id
  github:           mohsaad
  #  stackoverflow:    your-id
  #  quora:            your-id
  linkedin:         mohsaad
  #  pinterest:        your-id
  #  googlePlus:       your-id
  instagram:        mohsaad023
  #  reddit:           your-id
  #  medium:           your-id
  #  tumblr:           your-id
  #  email:            your-id@your-email.com

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Los_Angeles
permalink:          /blog/:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /blog/page:num/
# Navigation
nav:
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Reading list"
    url:            "/reading"
  - name:           "Quotes"
    url:            "/quotes"
  - name:           "Resume"
    url:            "/../"

copyright:
  year:             2020
  name:             Mohammad Saad

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "mohsaad23"

# needed for travis-ci build
exclude: [vendor, _old]
