highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
rdiscount:
  extensions: [smart]
permalink: :title.html
port: 8001
safe: false

title: Mohammad Saad's Resume
name: Mohammad Saad
nickname: mohsaad
email: saad@mohsaad.com
email_full: mailto:saad@mohsaad.com
website: https://mohsaad.com
website_full: https://mohsaad.com

url: "/"
baseurl: "/"

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from
  - jekyll-paginate


######################################
### Blog details
######################################
blog_url: "/blog"
blog_title: "mohsaad's blog"

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: true
    permalink: /blog/tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
permalink: /blog/:slug
timezone: America/New_York
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

Blog: /blog/posts.html

# Add general links to site pages here
links:
  Resume: /
  

# Add links for more focus here
# special_links:
#  "Search": https://duckduckgo.com

##################################
# TIL Section here
##################################
til_title: mohsaad's Today I Learned
til_author: mohsaad
til_subtitle: Daily Learnings

til_baseurl: "/til"

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Theme by rhl-bthr."

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /til/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

til_navbar:
 - name: "About"
   link: "about"
 - name: "Blog"
   link: "/blog"
 - name: "Resume"
   link: "/"
